name: Run mocha test
on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  run-mocha-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm test